runtime: python27
api_version: 1
threadsafe: true
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?\..*$
  - ^.local_storage/

libraries:
  - name: webapp2
    version: latest

handlers:
  - url: /.*
    script: techcubing.app
    secure: always
