runtime: python27
api_version: 1
threadsafe: true
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?\..*$
  - ^.local_storage/

libraries:
  - name: webapp2
    version: latest

handlers:
  - url: /static
    static_dir: src/static
    secure: always
  - url: /admin/.*
    script: admin.app
    login: admin
    secure: always
  - url: /.*
    script: techcubing.app
    secure: always
