java_binary(
    name = "main",
    srcs = ["Main.java"],
    main_class = "org.cubingusa.techcubing.Main",
    deps = [
        "//src/main/java/org/cubingusa/techcubing/framework:ServerState",
        "//src/main/java/org/cubingusa/techcubing/handlers:HomeHandler",
    ],
)
