proto_library(
    name = "person_proto",
    srcs = ["person.proto"],
)

java_proto_library(
    name = "person_java_proto",
    deps = [":person_proto"],
)

proto_library(
    name = "device_proto",
    srcs = ["device.proto"],
)

java_proto_library(
    name = "device_java_proto",
    deps = [":device_proto"],
)
