package(default_visibility = ["//visibility:public"])

java_library(
    name = "WcifUtil",
    srcs = ["WcifUtil.java"],
    deps = [
        "//src/main/java/org/cubingusa/techcubing/proto/wcif:round_java_proto",
    ],
)
